services:
  mrpv1:
    image: mrpv1
    container_name: mrpv1
    build:
      context: .
      dockerfile: mrpv1/Dockerfile
    ports: 
      - "80:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mrpv1net
  db:
    image: postgres
    container_name: mrpv1db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mrpv1db
    healthcheck:
      test: [ "CMD-SHELL", 'pg_isready -U "$${POSTGRES_USER:-postgres}" -d "$${POSTGRES_DB:-postgres}" -h localhost || exit 1' ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    stop_grace_period: 100s
    networks:
      - mrpv1net
    volumes:
      - mrpv1db:/var/lib/postgresql:rw
      - ./mrpv1/postgres/postgres.conf:/etc/postgresql/postgresql.conf:ro
      - ./mrpv1/postgres/init-scripts:/docker-entrypoint-initdb.d:ro
    command: [ "postgres", "-c", "config_file=/etc/postgresql/postgresql.conf", "-c", "log_statement=none", "-c", "log_min_duration_statement=1000", "-c", "log_connections=on", "-c", "log_disconnections=on" ]

volumes:
    mrpv1db:
      name: mrpv1dbvolume
networks:
    mrpv1net: